spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=securityg138
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8085